version: '3'

services:
  socmed-fe-dev:
    image: mikesudirman:socmed-fe
    build: ./socmed-fe
    # ports:
    #   - "3001:80"
    environment:
      - ENV=development

  # nginx:
  #   image: nginx:1.17-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #     # - 443:443
  #   volumes:
  #     - ./nginx-conf:/etc/nginx/conf.d
